### PR TITLE
fix: for react-testing-library to find dialog by `findByRole` with labe…

### PR DESCRIPTION
**Pull request by hedaukartik**
…lName as priority in rules on top of `findByLabelText`

### CODE REVIEW

**Comment by khedau** [comment]
With reference to the issue raise in antd repo- https://github.com/ant-design/ant-design/issues/35392

By this PR we will still be able to query modal by role `screen.getByRole('dialog', { name: 'dialog1'})` in https://dialog-ddwo9c8j1-react-component.vercel.app/demo/ant-design

**Comment by hedaukartik** [comment]
With reference to the issue raise in antd repo- https://github.com/ant-design/ant-design/issues/35392

By this PR we will still be able to query modal by role `screen.getByRole('dialog', { name: 'dialog1'})` in https://dialog-ddwo9c8j1-react-component.vercel.app/demo/ant-design

**Comment by hedaukartik** [comment]
@zombieJ  can you please check this breaking change?

**Comment by JeffreyATW** [comment]
@hedaukartik Shouldn't you be removing the `aria-labelledby` from https://github.com/react-component/dialog/blob/master/src/Dialog/index.tsx as well?

**Comment by dgreene1** [comment]
@hedaukartik which screen readers did you test this in?

**Comment by JeffreyATW** [comment]
Let's say I have a dialog with a title of "Foo".

When I test the dialog prior to the change in #285, it reads "Foo, web dialog".

When I test the dialog after the change in #285 using VoiceOver on macOS Safari, it reads "web dialog".

After this change, it reads "Foo, web dialog" again.

**Comment by dgreene1** [comment]
Thank you for that information @JeffreyATW. I’ll back you up and ask Zombie to reopen the issue this is attached to.

btw, since it seems unlikely that the maintainers will let us bring RTL into this, can you add a unit test that emulated the get by role (with name) option? That way we can make sure that the regression (that this PR fixes) does not happen again?

I’m not sure what that would look like but I imagine it would be “find the label by ID of the dialog and make sure that it’s the ID of the title.”

**Comment by hedaukartik** [comment]
> @hedaukartik Shouldn't you be removing the `aria-labelledby` from https://github.com/react-component/dialog/blob/master/src/Dialog/index.tsx as well?

Yes. It seems unnecessary. Removed it now. Thanks for explaining this issue in detail @JeffreyATW

**Comment by hedaukartik** [comment]
@zombieJ please check

**Comment by zombieJ** [comment]
`+ rc-dialog@8.8.2`

**Pull request merged**
