### PR TITLE
fix: dialog dont close when mouseDown in content and mouseUp in wrapper

### PR DESCRIPTION
**Pull request by littleee**
ref https://github.com/ant-design/ant-design/issues/27391

### CODE REVIEW

**Comment by ThreshHNS** [comment]
Thank you! Waiting for these changes in the release version.

**Comment by scotthwsnyder** [comment]
This is particularly bad when the Dialog has a child TextArea.  I'll try to select the contents of the TextArea with my mouse and accidentally mouseup outside of the dialog, closing everything.  Glad to see a fix is coming.  Any idea when this will make it in to master?

**Comment by afc163** [comment]
Conflicting

**Comment by littleee** [comment]
> Conflicting

done

**Comment by zombieJ** [comment]
`+ rc-dialog@8.4.4`

**Pull request merged**
