### PR TITLE
feat: add disableFocus prop

### PR DESCRIPTION
**Pull request by shaodahong**
Fixes https://github.com/react-component/dialog/issues/95
Fixes https://github.com/ant-design/ant-design/issues/19771

### CODE REVIEW

**Comment by afc163** [comment]
How about `focusTriggerAfterClose`?

**Comment by shaodahong** [comment]
> How about `focusTriggerAfterClose`?

look good, but maybe we set that default value is `true`

**Comment by running-snail-sfs** [comment]
> > How about `focusTriggerAfterClose`?
> 
> look good, but maybe we set that default value is `true`
 focusTriggerAfterClose: false,有效，官方文档是否更新下

**Comment by xrkffgg** [comment]
@running-snail-sfs 来个 PR

**Pull request merged**
