### PR TITLE
Fix focus trap tabbing behaviour 

### PR DESCRIPTION
**Pull request by wahiche-ideal**
Fixes https://github.com/ant-design/ant-design/issues/40380
close #360

### CODE REVIEW

**Comment by yoyo837** [comment]
LTGM

**Comment by khalibloo** [comment]
When is the next release scheduled? Looks like the last one was quite a while ago.

**Comment by wahiche-ideal** [comment]
There have been many releases since this was merged and accepted, when will this get into a release?

**Comment by yoyo837** [comment]
We already published it out.

**Comment by khalibloo** [comment]
Hmm, I don't think the issue got fixed then. At least not in the antd docs. The issue is still present.

**Comment by wahiche-ideal** [comment]
In what release did it get added?

**Comment by yoyo837** [comment]
[antd@5.15.0](https://github.com/ant-design/ant-design/releases/tag/5.15.0)

**Comment by wahiche-ideal** [comment]
I do not see it in the 5.15.0 list of items.  Are you sure it has been merged?

**Pull request merged**
